### ISSUE TITLE
How do you use the compiler

### ISSUE THREAD

**Issue by Pandademic** [UnvLabs/JavaScript#1]
Do you need a deno runtime?

**Comment by ksenginew** [comment]
Currently both compiler and compiled code works on formal JavaScript runtimes(Node.js, web browsers, Deno)

Is it ok or anything else?

> Please mention me as @ksenginew if I'm late to reply.

**Comment by Pandademic** [comment]
It's great , I was confused about running the compiler

**Comment by ksenginew** [comment]
@Pandademic Compiler is recently updated. please use the recent code.
Eg:-
```js
/* copy compiler.js here(https://github.com/UnvLabs/JavaScript/blob/main/compiler.js) */

console.log(compile(`
import print from 'standard'

if 'Unv is awesome!'
    print('Hello World!')
# keep editing for live results
`)) // tada
```

**Comment by Pandademic** [comment]
OK
